### ISSUE TITLE
"처음 만난날" 내용구성 항목

### ISSUE THREAD

**Issue by mrwebc** [mrwebc/community#1]
어떤 내용으로 구성해야 할까요?

좋은 아이디어를 댓글로 달아주세요

**Comment by mvcweb75** [comment]
처음 만나게 된 사연

**Comment by mrwebc** [comment]
전화부스 앞에서 기다리다 저만치 먼 곳에서 연두색 스웨터을 입고 무릅을 굽혀 활짝 웃는 모습의 그녀를 처음 보았습니다. 그녀는 이렇게 생각하고 있었데요. "그냥 집에 가야하나?" ㅋㅋㅋ

**Comment by mvcweb75** [comment]
처음 만난날 어떤 이벤트를 진행했나요?

**Comment by mrwebc** [comment]
닭갈비 먹고 노래방에 가서 18번 메들리로 좋은 이미지를 주었어요.
"신승훈의 보이지 않는 사랑~! 등등"
